attributes:
  metadata:
    restrictions:
      - condition: "not (cluster:net_provider == 'neutron' and networking_parameters:segmentation_type == 'vlan')"
        action: hide
  use_gbp:
    type: "checkbox"
    weight: 30
    value: false
    label: "Group-Based Policy"
    description: "Enable/Disable Group-Based Policy installation"
    restrictions:
      - condition: "not (cluster:net_provider == 'neutron' and (networking_parameters:segmentation_type == 'vlan' or networking_parameters:segmentation_type == 'gre'))"
        action: disable
  use_apic:
    type: "checkbox"
    weight: 31
    value: false
    label: "APIC Driver"
    description: "Enable/Disable APIC API Controller"
    restrictions:
      - condition: "not (cluster:net_provider == 'neutron' and networking_parameters:segmentation_type == 'vlan')"
        action: disable
  driver_type:
    type: "radio"
    weight: 33
    value: "ML2"
    label: "APIC Driver mode"
    restrictions:
      - condition: "settings:cisco_aci.use_apic.value != true"
        action: disable
    values:
      - data: "ML2"
        label: "ML2"
        description: "ML2 Driver"
      - data: "GBP"
        label: "GBP"
        description: "Group-Based Policy Driver"
        restrictions:
          - condition: "settings:cisco_aci.use_gbp.value != true"
            action: disable
  apic_hosts:
    value: '10.0.0.100'
    label: 'APIC Host'
    description: 'Comma­separated list of Cisco APIC IP addresses'
    weight: 41
    type: "text"
    restrictions:
      - condition: "settings:cisco_aci.use_apic.value != true"
        action: disable
  apic_username:
    value: 'admin'
    label: 'APIC Username'
    description: 'Username for Cisco APIC; usually admin is used to allow configuration for multiple tenants'
    weight: 42
    type: "text"
    regex:
      source: '\S'
      error: "Error field cannot be empty"
    restrictions:
      - condition: "settings:cisco_aci.use_apic.value != true"
        action: disable
  apic_password:
    value: 'password'
    label: 'APIC Password'
    description: 'Password for the Cisco APIC user identified by the username'
    weight: 43
    type: "password"
    regex:
      source: '\S'
      error: "Error field cannot be empty"
    restrictions:
      - condition: "settings:cisco_aci.use_apic.value != true"
        action: disable
  use_lldp:
    type: "checkbox"
    weight: 50
    value: false
    label: "Use lldp"
    description: "Try to automatically discover hosts"
    restrictions:
      - condition: "settings:cisco_aci.use_apic.value != true"
        action: disable
  static_config:
    type: "textarea"
    weight: 51
    value: ""
    label: "Static config"
    description: "Example:\n[apic_switch:201]\ncompute11,compute21=1/10\ncompute12=1/11\n"
    restrictions:
      - condition: "settings:cisco_aci.use_lldp.value != false or settings:cisco_aci.use_apic.value != true"
        action: disable
  additional_config:
    type: "textarea"
    weight: 52
    value: ""
    label: "Additional config"
    description: "Example:\n[DEFAULT]\napic_vpc_pairs=201:202,203:204"
    restrictions:
      - condition: "settings:cisco_aci.use_apic.value != true"
        action: disable
  ext_net_enable:
    type: "checkbox"
    weight: 70
    value: false
    label: "Configure external network"
    description: "Create external neutron network"
    restrictions:
      - condition: "settings:cisco_aci.use_apic.value != true"
        action: disable
  ext_net_name:
    type: "text"
    weight: 71
    value: "myextnet"
    label: "Network name:"
    description: "External network name"
    restrictions:
        - condition: "settings:cisco_aci.ext_net_enable.value == false"
          action: hide
  ext_net_subnet:
    type: "text"
    weight: 72
    value: "10.0.0.0/24"
    label: "Subnet range:"
    description: "CIDR for external network"
    restrictions:
        - condition: "settings:cisco_aci.ext_net_enable.value == false"
          action: hide
  ext_net_gateway:
    type: "text"
    weight: 73
    value: "10.0.0.1"
    label: "Gateway IP:"
    description: "IP address of the external gateway"
    restrictions:
        - condition: "settings:cisco_aci.ext_net_enable.value == false"
          action: hide
  ext_net_switch:
    type: "text"
    weight: 74
    value: "203"
    label: "Switch ID:"
    description: "Switch ID from Cisco APIC"
    restrictions:
        - condition: "settings:cisco_aci.ext_net_enable.value == false"
          action: hide
  ext_net_port:
    type: "text"
    weight: 75
    value: "1/34"
    label: "Port ID:"
    description: "Switch port to which the external router is connected"
    restrictions:
        - condition: "settings:cisco_aci.ext_net_enable.value == false"
          action: hide
